/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   ApiDemoPage.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html, render} from 'lit-html';

export {ApiDemoPageBase};

/**
 * Base class for API components demo page.
 * It creates basic sceleton for API demo page.
 *
 * Usage
 *
 * ```javascript
 * import { html, render } from 'lit-html';
 * import {ApiDemoPageBase} from '@advanced-rest-client/arc-demo-helper/ApiDemoPage.js';
 *
 * class ApiDemo extends ApiDemoPageBase {
 *  render() {
 *    render(html`
 *    ${this.headerTemplate()}
 *    <section role="main" class="vertical-section-container centered main">
 *      ${this._apiNavigationTemplate()}
 *      ...
 *    </section>
 *    `);
 *  }
 * }
 * const instance = new ApiDemo();
 * instance.render();
 * ```
 */
declare class ApiDemoPageBase {
  constructor();

  /**
   * Creates setters and getters to properties defined in the passed list of properties.
   * Property setter will trigger render function.
   *
   * @param props List of properties to initialize.
   */
  initObservableProperties(props: Array<String|null>|null): void;
  _setObservableProperty(prop: any, value: any): void;
  _apiChanged(e: any): void;
  _loadFile(file: any): any;

  /**
   * This method to be overriten in child class to handle navigation.
   *
   * @param e Dispatched navigation event
   */
  _navChanged(e: CustomEvent|null): void;
  _darkThemeHandler(e: any): void;
  _narrowHandler(e: any): void;
  _stylesHandler(e: any): void;

  /**
   * This method to be overriten in child class to render API options.
   *
   * @returns HTML template for apis dropdown options.
   */
  _apiListTemplate(): object|null;
  _apiNavigationTemplate(): any;

  /**
   * Abstract method. When not overriding `render()` method you can use
   * this function to render content inside the standar API components layout.
   *
   * ```
   * contentTemplate() {
   *  return html`<p>Demo content</p>`;
   * }
   * ```
   */
  contentTemplate(): void;

  /**
   * Call this on the top of the `render()` method to render demo navigation
   *
   * @returns HTML template for demo header
   */
  headerTemplate(): object|null;
  render(): void;
  _render(): void;
}
