/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ArcInteractiveDemo.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html, LitElement} from 'lit-element';

export {ArcInteractiveDemo};

declare class ArcInteractiveDemo extends LitElement {
  readonly tabs: any;
  selectedState: any;
  opened: any;
  constructor();
  firstUpdated(): void;
  render(): any;
  _stateChangeHandler(e: any): void;
  _toggleOptions(): void;
  _updateTabsAnimation(): void;
  _updateOptionsTabindex(): void;
  _activateOptionNode(node: any): void;
  _deactivateOptionNode(node: any): void;
  _tabsTemplate(): any;
  _triggerTemplate(): any;
  _configTemplate(): any;
}
